site_name: "LUMI-BE training materials"
site_url: https://klust.github.io/LUMI-BE-training-materials

theme:
  name: material
  greetings: Welcome to the LUMI-BE training materials"
  #custom_dir: site_customisations_LUMI
  custom_dir: site_customisations
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    - navigation.top
    - navigation.indexes
    - header.autohide
    - toc.follow
  #favicon: assets/favicon-LUMI.png
  font: false
  palette:
    scheme: lumi-be
  icon:
    logo: logo
    admonition:
      demo: fontawesome/solid/computer-mouse
      exercise: fontawesome/solid/screwdriver-wrench
      remark: fontawesome/solid/comment-dots
      bug: fontawesome/solid/robot
      audience: fontawesome/solid/people-group
      solution: fontawesome/solid/wand-magic-sparkles
      technical: fontawesome/solid/book-open-reader
      intermediate: fontawesome/solid/graduation-cap
      advanced: fontawesome/solid/user-graduate
      lumi-be: fontawesome/solid/building-flag
      nice-to-know: fontawesome/regular/lightbulb

nav:
  - Home: index.md
  #- "LUMI Intro 10/23":
  - "LUMI Intro (evolving)":
    - Overview: intro-evolving/index.md
    #- Schedule: intro-evolving/schedule.md
    - Intro to the notes: intro-evolving/00_Introduction.md
    - Architecture: intro-evolving/01_Architecture.md
    - Programming Environment: intro-evolving/02_CPE.md
    - Getting access: intro-evolving/03_LUMI_access.md
    - Modules: intro-evolving/04_Modules.md
    - Software stacks: intro-evolving/05_Software_stacks.md
    - Exercises 1: intro-evolving/06_Exercises_1.md
    - Slurm on LUMI: intro-evolving/07_Slurm.md
    - Binding: intro-evolving/08_Binding.md
    - Exercises 2: intro-evolving/09_Exercises_2.md
    - Lustre: intro-evolving/10_Lustre.md
    - Containers: intro-evolving/11_Containers.md
    - Support: intro-evolving/12_Support.md
    - A1 Slurm issues: intro-evolving/A01_Slurm_issues.md
    - A2 Documentation: intro-evolving/A02_Documentation.md
     
plugins:
  # show revision date at bottom of each page
  # - git-revision-date-localized
  # necessary for search to work
  - search
  # redirects to avoid broken URLs in original version of the tutorial (June 2020)
  - redirects:
      redirect_maps:
          intro.md: intro-evolving/index.md
          intro-latest.md: intro-evolving/index.md

markdown_extensions:
  # Attributes (e.g., for lazy loading)
  - attr_list
  # Markdown in HTML
  - md_in_html
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
 
#extra:
  # add links in bottom right
  #social:
      #- type: github
      #icon: octicons/logo-github
      #link: https://github.com/easybuilders
    #- icon: fontawesome/brands/youtube
    #  link: https://www.youtube.com/channel/UCb31KOJ6Wqu0sRpIRi_k8Mw
    #  name: LUMI on YouTube
    #- icon: fontawesome/brands/linkedin
    #  link: https://www.linkedin.com/company/lumi-supercomputer
    #  name: LUMI on LinkedIn
    #- icon: fontawesome/brands/twitter
    #  link: https://twitter.com/LUMIhpc
    #  name: LUMI on Twitter
